// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6EIQFp-BOECDMJ-GLkTgBqcQEkoklWr0',
    appId: '1:419667414394:web:caa3e9891382ba5834dac3',
    messagingSenderId: '419667414394',
    projectId: 'adminpanel-new-2024',
    authDomain: 'adminpanel-new-2024.firebaseapp.com',
    storageBucket: 'adminpanel-new-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6EIQFp-BOECDMJ-GLkTgBqcQEkoklWr0',
    appId: '1:419667414394:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '419667414394',
    projectId: 'adminpanel-new-2024',
    storageBucket: 'adminpanel-new-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6EIQFp-BOECDMJ-GLkTgBqcQEkoklWr0',
    appId: '1:419667414394:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '419667414394',
    projectId: 'adminpanel-new-2024',
    storageBucket: 'adminpanel-new-2024.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6EIQFp-BOECDMJ-GLkTgBqcQEkoklWr0',
    appId: '1:419667414394:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '419667414394',
    projectId: 'adminpanel-new-2024',
    storageBucket: 'adminpanel-new-2024.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
